version: "3"
services:
  php:
    build: .
    volumes:
      - ./web:/var/www/html/cake_starter
      - ./php/php.ini:/usr/local/etc/php/php.ini
    tty: true
    ports:
     - 80:80
  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lotteryapp
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3307:3306

volumes:
  db-data:
    external: false